### ISSUE TITLE
Printing of sqrt as sqrtm

### ISSUE THREAD

**Issue by baggepinnen** [MilesCranmer/SymbolicRegression.jl#11]
I notched that `sqrt` is printed as `sqrtm`, is this intentional or a typo?
```julia
12          1.963e+01  6.172e-02  (((46.020115 - x1) - x1) - ((sqrtm(x3) / 0.389079) / 0.5039604))
```

**Comment by MilesCranmer** [comment]
This is intentional. The package requires all operators to accept negative and positive numbers, so I map sqrt, log, and ^ to operators with absolute value on their arguments: sqrtm = sqrt(abs(x)) (https://pysr.readthedocs.io/en/latest/docs/operators/). Normally the user should define these mappings, but the sqrt, log, and pow errors are common enough in PySR that I just map the operators automatically instead of erroring.

**Comment by MilesCranmer** [comment]
I guess I should rename these to be sqrt_abs, log_abs, etc., to be more obvious! Will add this.

**Comment by MilesCranmer** [comment]
Will be in v0.3.4
