### ISSUE TITLE
Is it possible to include function composition ∘ as a binary operator?

### ISSUE THREAD

**Issue by azev77** [MilesCranmer/SymbolicRegression.jl#19]
Hi and thanks for this package! 
I mentioned this on [discourse](https://discourse.julialang.org/t/ann-symbolicregression-jl-distributed-symbolic-regression/54853/2?u=albert_zevelev): 
Is it possible to include function composition ∘ as a binary operator?

**Comment by MilesCranmer** [comment]
Thanks for posting here too, @azev77. 
I thought about this again; what equations would be possible with this operator that wouldn't be possible without it? It should already be capable of composing operators in a tree.

I could see other operators like differential operators being of interest. But all of these would require a lot of internal changes to get working, and the algorithm for evaluating them would be slower (I think).

Cheers,
Miles

**Comment by MilesCranmer** [comment]
I don't see such functionality on the horizon, so am closing this. Will re-open if I make the package capable of handling more flexible operators. The reason I do not currently is because having a small set of allowable operators (real -> real and real,real->real) allows me to make some significant optimizations.
