### ISSUE TITLE
Gradient-based loss functions

### ISSUE THREAD

**Issue by jeeva2812** [MilesCranmer/SymbolicRegression.jl#77]
I am interested in finding a way to modify the loss function in PySR. As in, getting the expression, giving to a different function which gives the loss, rather than having a prediction as such.

I was unable to understand EvaluateEquation.jl, which I believe is required to implement the same. If anyone can spare time, please do let me know whether modifying the loss/score is possible. Thanks in advance.

**Comment by MilesCranmer** [comment]
Hi @jeeva2812,

You can pass an arbitrary loss function to PySR using, e.g., `loss="myloss(x, y) = abs(x - y)"`.

SymbolicRegression.jl is similar - you can pass any function (`R x R -> [0, inf)`) to the `loss` argument of `Options()`.

Cheers,
Miles

**Comment by jeeva2812** [comment]
Hello @MilesCranmer, thank you so much for your response. 

However, my query is more on the lines of evaluating the equation as such, as in, if I don't have the actual expected values but have the divergence or curl of the expected function at various points.

**Comment by MilesCranmer** [comment]
I see. I would be very interested in this! cc @kazewong

So, for starters, have a look at https://github.com/MilesCranmer/SymbolicRegression.jl/pull/39. This PR (which I still need to merge) implements a very high-performance autodiff routine for an arbitrary expression using Zygote.jl and the same tree-based evaluation as used currently. For instance, `evaldiffTreeArray(tree, input_data, options, i)` will evaluate the gradient of an expression with respect to `x[i]` input feature.

If you use that function `evaldiffTreeArray`, you could in theory learn an expression that gives you a particular divergence or curl. 

Then, you will need to modify the function `EvalLoss` in `src/LossFunctions.jl` to call `evaldiffTreeArray` instead of `evalTreeArray`: https://github.com/MilesCranmer/SymbolicRegression.jl/blob/6d045597823492e34e83814bd536aaa3f5b518d2/src/LossFunctions.jl#L25-L41, and modify the loss calculation accordingly.

You might also need to change the `Dataset` structure to allow for additional data, like the divergence data (right now it simply stores `y`-the desired output)

**Comment by MilesCranmer** [comment]
By the way, to help you understand the equation evaluation, I would look at these functions: https://github.com/MilesCranmer/SymbolicRegression.jl/blob/6d045597823492e34e83814bd536aaa3f5b518d2/src/EvaluateEquation.jl#L291-L326

They are equivalent to `evalTreeArray`, but without the optimizations. Basically, to evaluate a given tree representing an expression, you do the following recursion (pseudocode):

```
function eval(current_node)
    if current_node is leaf
        return current_node.value
    elif current_node is degree 1
        return current_node.operator(current_node.left_child)
    else
        return current_node.operator(current_node.left_child, current_node.right_child)
```
all the rest of the code in that function is optimizations and checks for NaNs/Infs.

**Comment by jeeva2812** [comment]
Thank you so much, I will take a look into it.
