### ISSUE TITLE
forcing variables to regression

### ISSUE THREAD

**Issue by geek-mr-xie** [MilesCranmer/SymbolicRegression.jl#87]
i have a function like f(x,y).
but the regression result only have f(y).
the MSE is about 1.0 of 6000 points sample.

**Comment by MilesCranmer** [comment]
If you only have two variables, then 6000 points is overkill. I would try
with ~100 points. It is likely the equations are taking too long to
evaluate and it simply has not tried very many.

Alternatively,

(1) if your data is very noisy, which is why you are using 6000, you could
turn on denoising with (denoise=True). If you are doing this, you would
want to pass Xresampled as an array of random ~100 points within the domain
of your data. (i.e.,
```
Xresampled = np.random.rand(100, 2)
Xresampled[:, 0] = Xresampled[:, 0] * (xmax - xmin) + xmin
Xresampled[:, 1] = Xresampled[:, 1] * (ymax - ymin) + ymin
model = PySRRegressor(..., denoise=True, Xresampled=Xresampled)
```

(2) You could try turning on batching (batching=True), and set some
batchSize to some small number. This way it will still evaluate on all 6000
points at the final stages, but will evaluate on a random selection during
the search.

**Comment by geek-mr-xie** [comment]
Thanks for your patient reply. I am trying to run my julia script again. The variable x back to my formular. 
But the MSE is still around 1.0.

**Comment by geek-mr-xie** [comment]
Your (2) is very useful, by setting the batching true  my x back again.

**Comment by MilesCranmer** [comment]
Awesome, glad to hear it works.
